import requests
from credentials import auth_url

app_key = '<generated by create_app_key.py>'
user_sid = '<UUID of the user from Keycloak>'

r = requests.get(auth_url + '/token',
    headers={
        'Authorization': 'Basic {0}'.format(app_key)
    },
    params={
        'uid': user_sid,
        'provider':'keycloak_openid',
        'scope':'openid'}, verify=False)

print(r.status_code)
print(r.text)